// Customizer const
export const TOGGLE_COLLAPSED_NAV = "TOGGLE_COLLAPSE_MENU";
export const WINDOW_WIDTH = "WINDOW-WIDTH";
export const SWITCH_LANGUAGE = "SWITCH-LANGUAGE";

//Contact Module const
export const FETCH_START = "fetch_start";
export const FETCH_SUCCESS = "fetch_success";
export const FETCH_ERROR = "fetch_error";
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const SHOW_MESSAGE_LOGIN = "SHOW_MESSAGE_LOGIN";
export const SHOW_MESSAGE_FORGOT = "SHOW_MESSAGE_FORGOT";
export const HIDE_MESSAGE = "HIDE_MESSAGE";
export const HIDE_DOCUMENT_MESSAGE = "HIDE_DOCUMENT_MESSAGE";
export const ON_SHOW_LOADER = "ON_SHOW_LOADER";
export const ON_HIDE_LOADER = "ON_HIDE_LOADER";

//Auth const
export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNIN_GOOGLE_USER = "SIGNIN_GOOGLE_USER";
export const SIGNIN_GOOGLE_USER_SUCCESS = "SIGNIN_GOOGLE_USER_SUCCESS";
export const SIGNIN_FACEBOOK_USER = "SIGNIN_FACEBOOK_USER";
export const SIGNIN_FACEBOOK_USER_SUCCESS = "SIGNIN_FACEBOOK_USER_SUCCESS";
export const SIGNIN_TWITTER_USER = "SIGNIN_TWITTER_USER";
export const SIGNIN_TWITTER_USER_SUCCESS = "SIGNIN_TWITTER_USER_SUCCESS";
export const SIGNIN_GITHUB_USER = "SIGNIN_GITHUB_USER";
export const SIGNIN_GITHUB_USER_SUCCESS = "signin_github_user_success";
export const SIGNIN_USER = "SIGNIN_USER";
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
export const SIGNOUT_USER = "SIGNOUT_USER";
export const SIGNOUT_USER_SUCCESS = "SIGNOUT_USER_SUCCESS";
export const INIT_URL = "INIT_URL";

//Get Area Data
export const GET_AREA = "GET_AREA";
export const GET_AREA_SUCCESS_DATA = "GET_AREA_SUCCESS_DATA";
export const SAVE_AREA_DATA = "SAVE_AREA_DATA";
export const DELETE_AREA_DATA = "DELETE_AREA_DATA";

//Get Department Data
export const GET_DEPARTMENT = "GET_DEPARTMENT";
export const GET_DEPARTMENT_SUCCESS_DATA = "GET_DEPARTMENT_SUCCESS_DATA";
export const SAVE_DEPARTMENT_DATA = "SAVE_DEPARTMENT_DATA";
export const DELETE_DEPARTMENT_DATA = "DELETE_DEPARTMENT_DATA";

//Get Service Data
export const GET_SERVICE = "GET_SERVICE";
export const GET_SERVICE_SUCCESS_DATA = "GET_SERVICE_SUCCESS_DATA";
export const SAVE_SERVICE_DATA = "SAVE_SERVICE_DATA";
export const DELETE_SERVICE_DATA = "DELETE_SERVICE_DATA";

//Get Process Data
export const GET_PROCESS_DATA = "GET_PROCESS_DATA";
export const GET_PROCESS_SUCCESS_DATA = "GET_PROCESS_SUCCESS_DATA";
export const GET_PROCESS_WORK_INSTRUCTION_DATA =
  "GET_PROCESS_WORK_INSTRUCTION_DATA";
export const GET_PROCESS_WORK_ISTRUCTION_SUCCESS_DATA =
  "GET_PROCESS_WORK_ISTRUCTION_SUCCESS_DATA";
export const GET_PROCESS_DROPDOWN = "GET_PROCESS_DROPDOWN";
export const GET_PROCESS_DROPDOWN_SUCCESS = "GET_PROCESS_DROPDOWN_SUCCESS";
export const SAVE_PROCESS_DATA = "SAVE_PROCESS_DATA";
export const DELETE_PROCESS_DATA = "DELETE_PROCESS_DATA";

//Get Procedure Data
export const GET_PROCEDURE = "GET_PROCEDURE";
export const GET_PROCEDURE_SUCCESS_DATA = "GET_PROCEDURE_SUCCESS_DATA";
export const GET_MOREAPPFORMDATA_DATA = "GET_MOREAPPFORMDATA_DATA";
export const GET_MOREAPPFORMDATA_SUCCESS_DATA =
  "GET_MOREAPPFORMDATA_SUCCESS_DATA";
export const GET_MOREAPPFORMDATA_FAIL_DATA = "GET_MOREAPPFORMDATA_FAIL_DATA";
export const GET_DEVICE_DATA = "GET_DEVICE_DATA";
export const GET_DEVICE_SUCCESS_DATA = "GET_DEVICE_SUCCESS_DATA";
export const SAVE_PROCEDURE_DATA = "SAVE_PROCEDURE_DATA";
export const UPDATE_PROCEDURE_DATA = "UPDATE_PROCEDURE_DATA";
export const DELETE_PROCEDURE_DATA = "DELETE_PROCEDURE_DATA";
export const GET_DETAIL_PROCEDURE = "GET_DETAIL_PROCEDURE";
export const GET_DETAIL_PROCEDURE_SUCCESS_DATA =
  "GET_DETAIL_PROCEDURE_SUCCESS_DATA";
export const SAVE_PROCEDURE_LAUNCH_DATA = "SAVE_PROCEDURE_LAUNCH_DATA";

//Get Area, Department & Service DropDown
export const GET_DROPDOWN = "GET_DROPDOWN";
export const GET_DROPDOWN_SUCCESS_DATA = "GET_DROPDOWN_SUCCESS_DATA";

//Sticky
export const GET_STICKY = "GET_STICKY";
export const NOTES_UPDATE = "NOTES_UPDATE";
export const FETCH_ALL_NOTES_SUCCESS = "FETCH_ALL_NOTES_SUCCESS";
export const UPDATE_ALL_NOTES_SUCCESS = "UPDATE_ALL_NOTES_SUCCESS";

//Contact
export const GET_All_CONTACT_SUCCESS = "GET_All_CONTACT_SUCCESS";
export const ON_ADD_CONTACT_SUCCESS = "ON_ADD_CONTACT_SUCCESS";
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";

// File upload
export const UPLOAD_REQUEST = "UPLOAD_REQUEST";
export const UPLOAD_PROGRESS = "UPLOAD_PROGRESS";
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAILURE = "UPLOAD_FAILURE";

//Get Visits Data
export const VISITS_STATUS_SHOW_SUCCESS_MESSAGE =
  "VISITS_STATUS_SHOW_SUCCESS_MESSAGE";
export const GET_VISITS = "GET_VISITS";
export const GET_VISITS_SUCCESS_DATA = "GET_VISITS_SUCCESS_DATA";
export const GET_VISITS_REPORT_SUCCESS_DATA = "GET_VISITS_REPORT_SUCCESS_DATA";
export const GET_VISITS_REPORT = "GET_VISITS_REPORT";
export const SAVE_VISIT_DATA = "SAVE_VISIT_DATA";
export const GET_PROCEDURE_TYPE = "GET_PROCEDURE_TYPE";
export const GET_PROCEDURE_TYPE_SUCCESS = "GET_PROCEDURE_TYPE_SUCCESS";
export const READ_DESKO_SERVICE_DATA = "READ_DESKO_SERVICE_DATA";
export const GET_DESKO_SERVICE_DATA_SUCCESS = "GET_DESKO_SERVICE_DATA_SUCCESS";
export const SAVE_VISIT_DATA_SUCCESS = "SAVE_VISIT_DATA_SUCCESS";
export const SAVE_VISIT_DATA_UNSUCCESS = "SAVE_VISIT_DATA_UNSUCCESS";
export const GET_IDENTITY_DETAIL = "GET_IDENTITY_DETAIL";
export const GET_IDENTITY_DETAIL_SUCCESS_DATA =
  "GET_IDENTITY_DETAIL_SUCCESS_DATA";
export const GET_SCHEDULE_VISIT = "GET_SCHEDULE_VISIT";
export const GET_SCHEDULE_VISIT_SUCCESS_DATA =
  "GET_SCHEDULE_VISIT_SUCCESS_DATA";
export const ADD_VISIT_STATUS_CHANGE = "ADD_VISIT_STATUS_CHANGE";
export const ADD_IDENTITY_STATUS_CHANGE = "ADD_IDENTITY_STATUS_CHANGE";
export const GET_SCHEDULED_VISIT_STATUS_CHANGE =
  "GET_SCHEDULED_VISIT_STATUS_CHANGE";
export const SAVE_TYPE_STATUS_CHANGE = "SAVE_TYPE_STATUS_CHANGE";
export const SAVING_TYPE_STATUS_CHANGE = "SAVING_TYPE_STATUS_CHANGE";
export const CLOSE_MODAL_AFTER_SUCCESS = "CLOSE_MODAL_AFTER_SUCCESS";
export const GET_SCHEDULE_VISITS_LIST = "GET_SCHEDULE_VISITS_LIST";
export const GET_SCHEDULE_VISIT_LIST_SUCCESS_DATA =
  "GET_SCHEDULE_VISIT_LIST_SUCCESS_DATA";
export const GET_EVENT_AND_INVITEES = "GET_EVENT_AND_INVITEES";
export const GET_SCHEDULE_STATUS_CHANGE = "GET_SCHEDULE_STATUS_CHANGE";
export const GET_SCHEDULE_STATUS_SUCCESS = "GET_SCHEDULE_STATUS_SUCCESS";
export const CLEAR_DESKO_DATA = "CLEAR_DESKO_DATA";

//Get Training Course Data
export const TRAINING_COURSE_STATUS_SHOW_SUCCESS_MESSAGE =
  "TRAINING_COURSE_STATUS_SHOW_SUCCESS_MESSAGE";
export const GET_TRAINING_COURSE = "GET_TRAINING_COURSE";
export const GET_TRAINING_COURSE_SUCCESS_DATA =
  "GET_TRAINING_COURSE_SUCCESS_DATA";
export const SAVE_APPROVE_DATA = "SAVE_APPROVE_DATA";
//export const GET_TRAINING_COURSE_REPORT_SUCCESS_DATA = 'GET_TRAINING_COURSE_REPORT_SUCCESS_DATA';
//export const GET_TRAINING_COURSE_REPORT = 'GET_TRAINING_COURSE_REPORT';

//Get Training Plan Data
export const TRAININGPLAN_STATUS_SHOW_SUCCESS_MESSAGE =
  "TRAININGPLAN_STATUS_SHOW_SUCCESS_MESSAGE";
export const GET_TRAININGPLAN = "GET_TRAININGPLAN";
export const GET_TRAININGPLAN_SUCCESS_DATA = "GET_TRAININGPLAN_SUCCESS_DATA";
export const GET_TRAININGPLAN_REPORT_SUCCESS_DATA =
  "GET_TRAININGPLAN_REPORT_SUCCESS_DATA";
export const GET_TRAININGPLAN_REPORT = "GET_TRAININGPLAN_REPORT";

export const SAVE_PLAN_DATA = "SAVE_PLAN_DATA";
export const DELETE_PLAN_DATA = "DELETE_PLAN_DATA";

//Dashboard Graphs
export const GET_ATTENDED_EMPLOYEE = "GET_ATTENDED_EMPLOYEE";
export const GET_ATTENDED_EMPLOYEE_SUCCESS_DATA =
  "GET_ATTENDED_EMPLOYEE_SUCCESS_DATA";
export const GET_TRAINING_STATUS_STATISTIC = "GET_TRAINING_STATUS_STATISTIC";
export const GET_TRAINING_STATUS_STATISTIC_SUCCESS_DATA =
  "GET_TRAINING_STATUS_STATISTIC_SUCCESS_DATA";
export const GET_TRAINING_HOURS = "GET_TRAINING_HOURS";
export const GET_TRAINING_HOURS_SUCCESS_DATA =
  "GET_TRAINING_HOURS_SUCCESS_DATA";
export const GET_PROGRESS_GOAL = "GET_PROGRESS_GOAL";
export const GET_PROGRESS_GOAL_SUCCESS_DATA = "GET_PROGRESS_GOAL_SUCCESS_DATA";
export const GET_PROGRESS_COUNTRY_WISE = "GET_PROGRESS_COUNTRY_WISE";
export const GET_PROGRESS_COUNTRY_WISE_SUCCESS_DATA =
  "GET_PROGRESS_COUNTRY_WISE_SUCCESS_DATA";

//Get Session Data
export const SESSION_STATUS_SHOW_SUCCESS_MESSAGE =
  "SESSION_STATUS_SHOW_SUCCESS_MESSAGE";
export const GET_SESSION = "GET_SESSION";
export const GET_SESSION_SUCCESS_DATA = "GET_SESSION_SUCCESS_DATA";
// export const GET_SESSION_REPORT_SUCCESS_DATA = 'GET_SESSION_REPORT_SUCCESS_DATA';
// export const GET_SESSION_REPORT = 'GET_SESSION_REPORT';

export const SAVE_SESSION_DATA = "SAVE_SESSION_DATA";
export const DELETE_SESSION_DATA = "DELETE_SESSION_DATA";

//Get Category Data
export const COST_STATUS_SHOW_SUCCESS_MESSAGE =
  "COST_STATUS_SHOW_SUCCESS_MESSAGE";
export const GET_COST = "GET_COST";
export const GET_COST_SUCCESS_DATA = "GET_COST_SUCCESS_DATA";
// export const GET_COST_REPORT_SUCCESS_DATA = 'GET_COST_REPORT_SUCCESS_DATA';
// export const GET_COST_REPORT = 'GET_COST_REPORT';

export const SAVE_COST_DATA = "SAVE_COST_DATA";
export const DELETE_COST_DATA = "DELETE_COST_DATA";

//Get Employee Work Logs Data
export const EMPLOYEES_STATUS_SHOW_SUCCESS_MESSAGE =
  "EMPLOYEES_STATUS_SHOW_SUCCESS_MESSAGE";
export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const GET_EMPLOYEES_SUCCESS_DATA = "GET_EMPLOYEES_SUCCESS_DATA";
export const GET_EMPLOYEES_REPORT_SUCCESS_DATA =
  "GET_EMPLOYEES_REPORT_SUCCESS_DATA";
export const GET_EMPLOYEES_REPORT = "GET_EMPLOYEES_REPORT";

//Get Procedures Data
export const PROCEDURES_STATUS_SHOW_SUCCESS_MESSAGE =
  "PROCEDURES_STATUS_SHOW_SUCCESS_MESSAGE";
export const GET_PROCEDURES = "GET_PROCEDURES";
export const GET_PROCEDURES_SUCCESS_DATA = "GET_PROCEDURES_SUCCESS_DATA";
export const GET_PROCEDURES_REPORT_SUCCESS_DATA =
  "GET_PROCEDURES_REPORT_SUCCESS_DATA";
export const GET_PROCEDURES_REPORT = "GET_PROCEDURES_REPORT";

export const GET_PROCEDURE_FORM = "GET_PROCEDURE_FORM";
export const GET_PROCEDURE_FORM_SUCCESS_DATA =
  "GET_PROCEDURE_FORM_SUCCESS_DATA";

export const CLOSE_PROCEDURE_MODAL = "CLOSE_PROCEDURE_MODAL";
export const OPEN_PROCEDURE_MODAL = "OPEN_PROCEDURE_MODAL";

//Get Documents Data
export const DOCUMENTS_STATUS_SHOW_SUCCESS_MESSAGE =
  "DOCUMENTS_STATUS_SHOW_SUCCESS_MESSAGE";
export const GET_DOCUMENTS = "GET_DOCUMENTS";
export const GET_DOCUMENTS_SUCCESS_DATA = "GET_DOCUMENTS_SUCCESS_DATA";
export const GET_DOCUMENTS_REPORT_SUCCESS_DATA =
  "GET_DOCUMENTS_REPORT_SUCCESS_DATA";
export const GET_DOCUMENTS_REPORT = "GET_DOCUMENTS_REPORT";

//Get Reports Data
export const REPORTS_STATUS_SHOW_SUCCESS_MESSAGE =
  "REPORTS_STATUS_SHOW_SUCCESS_MESSAGE";
export const GET_REPORTS = "GET_REPORTS";
export const GET_REPORTS_SUCCESS_DATA = "GET_REPORTS_SUCCESS_DATA";
export const GET_TRAINING_REPORTS = "GET_TRAINING_REPORTS";
export const GET_TRAINING_REPORTS_SUCCESS_DATA =
  "GET_TRAINING_REPORTS_SUCCESS_DATA";

//Get Inspections Data
export const INSPECTIONS_STATUS_SHOW_SUCCESS_MESSAGE =
  "INSPECTIONS_STATUS_SHOW_SUCCESS_MESSAGE";
export const GET_INSPECTIONS = "GET_INSPECTIONS";
export const GET_INSPECTIONS_SUCCESS_DATA = "GET_INSPECTIONS_SUCCESS_DATA";
export const GET_INSPECTIONS_REPORT_SUCCESS_DATA =
  "GET_INSPECTIONS_REPORT_SUCCESS_DATA";
export const GET_INSPECTIONS_REPORT = "GET_INSPECTIONS_REPORT";
export const GET_CALENDAR = "GET_CALENDAR";
export const GET_CALENDAR_SUCCESS_DATA = "GET_CALENDAR_SUCCESS_DATA";
export const GET_INITIAL_SIGNIN_STATUS = "GET_INITIAL_SIGNIN_STATUS";
export const GET_INITIAL_SIGNIN_STATUS_SUCCESS =
  "GET_INITIAL_SIGNIN_STATUS_SUCCESS";
export const SAVE_CALENDAR_DATA = "SAVE_CALENDAR_DATA";
export const SAVE_CALENDAR_SUCCESS_DATA = "SAVE_CALENDAR_SUCCESS_DATA";
export const VALIDATE_INITIAL_DIRECTORY = "VALIDATE_INITIAL_DIRECTORY";
export const VALIDATE_INITIAL_DIRECTORY_SUCCESS =
  "VALIDATE_INITIAL_DIRECTORY_SUCCESS";
export const SET_DIRECTORY_TOKEN = "SET_DIRECTORY_TOKEN";
export const SET_DIRECTORY_TOKEN_SUCCESS = "SET_DIRECTORY_TOKEN_SUCCESS";

//Get Collobrator Data
export const COLLOBRATOR_STATUS_SHOW_SUCCESS_MESSAGE =
  "COLLOBRATOR_STATUS_SHOW_SUCCESS_MESSAGE";
export const GET_COLLOBRATOR = "GET_COLLOBRATOR";
export const GET_COLLOBRATOR_SUCCESS_DATA = "GET_COLLOBRATOR_SUCCESS_DATA";
export const GET_COLLOBRATOR_COURSE_SUCCESS_DATA =
  "GET_COLLOBRATOR_COURSE_SUCCESS_DATA";
export const GET_COLLOBRATOR_COURSE = "GET_COLLOBRATOR_COURSE";

//Get Identities Data
export const GET_IDENTITIES = "GET_IDENTITIES";
export const GET_IDENTITIES_SUCCESS_DATA = "GET_IDENTITIES_SUCCESS_DATA";
export const IDENTITIES_STATUS_SHOW_SUCCESS_MESSAGE =
  "IDENTITIES_STATUS_SHOW_SUCCESS_MESSAGE";

export const GET_SINGLEIDENTITY = "GET_SINGLEIDENTITY";
export const GET_SINGLEIDENTITY_SUCCESS_DATA =
  "GET_SINGLEIDENTITY_SUCCESS_DATA";

//Get Select Identities Data
export const GET_SELIDENTITIES = "GET_SELIDENTITIES";
export const GET_SELIDENTITIES_SUCCESS_DATA = "GET_SELIDENTITIES_SUCCESS_DATA";
export const SELIDENTITIES_STATUS_SHOW_SUCCESS_MESSAGE =
  "SELIDENTITIES_STATUS_SHOW_SUCCESS_MESSAGE";

//Get Select Collobrator Data
export const GET_SELCOLLOBRATOR = "GET_SELCOLLOBRATOR";
export const GET_SELCOLLOBRATOR_SUCCESS_DATA =
  "GET_SELCOLLOBRATOR_SUCCESS_DATA";
export const SELCOLLOBRATOR_STATUS_SHOW_SUCCESS_MESSAGE =
  "SELCOLLOBRATOR_STATUS_SHOW_SUCCESS_MESSAGE";
export const CLOSE_SELCOLLOBRATOR_MODAL = "CLOSE_SELCOLLOBRATOR_MODAL";
export const OPEN_SELCOLLOBRATOR_MODAL = "OPEN_SELCOLLOBRATOR_MODAL";

export const GET_SELCOLLOBRATORNOASSIGN = "GET_SELCOLLOBRATORNOASSIGN";
export const GET_SELCOLLOBRATORNOASSIGN_SUCCESS_DATA =
  "GET_SELCOLLOBRATORNOASSIGN_SUCCESS_DATA";
export const SET_COURSE = "SET_COURSE";

//Get Expedient Data
export const EXPEDIENTS_STATUS_SHOW_SUCCESS_MESSAGE =
  "EXPEDIENTS_STATUS_SHOW_SUCCESS_MESSAGE";
export const GET_EXPEDIENTS = "GET_EXPEDIENTS";
export const GET_EXPEDIENTS_SUCCESS_DATA = "GET_EXPEDIENTS_SUCCESS_DATA";
export const GET_EXPEDIENTS_REPORT_SUCCESS_DATA =
  "GET_EXPEDIENTS_REPORT_SUCCESS_DATA";
export const GET_EXPEDIENTS_REPORT = "GET_EXPEDIENTS_REPORT";
export const GET_EXPEDIENT_FORM = "GET_EXPEDIENT_FORM";
export const GET_EXPEDIENT_FORM_SUCCESS_DATA =
  "GET_EXPEDIENT_FORM_SUCCESS_DATA";

export const CLOSE_EXPEDIENT_MODAL = "CLOSE_EXPEDIENT_MODAL";
export const OPEN_EXPEDIENT_MODAL = "OPEN_EXPEDIENT_MODAL";

// Get Expedient connected Documents
export const EXPDOCUMENTS_STATUS_SHOW_SUCCESS_MESSAGE =
  "EXPDOCUMENTS_STATUS_SHOW_SUCCESS_MESSAGE";
export const GET_EXPDOCUMENTS = "GET_EXPDOCUMENTS";
export const GET_EXPDOCUMENTS_SUCCESS_DATA = "GET_EXPDOCUMENTS_SUCCESS_DATA";

// Get Details Documents
export const DOCDOCUMENTS_STATUS_SHOW_SUCCESS_MESSAGE =
  "DOCDOCUMENTS_STATUS_SHOW_SUCCESS_MESSAGE";
export const GET_DOCDOCUMENTS = "GET_DOCDOCUMENTS";
export const GET_DOCDOCUMENTS_SUCCESS_DATA = "GET_DOCDOCUMENTS_SUCCESS_DATA";

// Get Visit, Procedure, Inspection connected Documents
export const ALLDOCUMENTS_STATUS_SHOW_SUCCESS_MESSAGE =
  "ALLDOCUMENTS_STATUS_SHOW_SUCCESS_MESSAGE";
export const GET_ALLDOCUMENTS = "GET_ALLDOCUMENTS";
export const GET_ALLDOCUMENTS_SUCCESS_DATA = "GET_ALLDOCUMENTS_SUCCESS_DATA";

//Get Identities Data
export const GET_GETREPORTS = "GET_GETREPORTS";
export const GET_GETREPORTS_SUCCESS_DATA = "GET_GETREPORTS_SUCCESS_DATA";
export const GETREPORTS_STATUS_SHOW_SUCCESS_MESSAGE =
  "GETREPORTS_STATUS_SHOW_SUCCESS_MESSAGE";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const OPEN_MODAL = "OPEN_MODAL";
export const GET_STATUS_INITIAL = "GET_STATUS_INITIAL";
export const GET_STATUS_STARTING = "GET_STATUS_STARTING";

export const CLOSE_SELIDENTITY_MODAL = "CLOSE_SELIDENTITY_MODAL";
export const OPEN_SELIDENTITY_MODAL = "OPEN_SELIDENTITY_MODAL";

export const SET_GLOBALDATA = "SET_GLOBALDATA";
export const CLOSE_BULKSIGNATURE_MODAL = "CLOSE_BULKSIGNATURE_MODAL";

export const GET_IDENTITY_BY_SESSION = "GET_IDENTITY_BY_SESSION";
export const GET_IDENTITY_BY_SESSION_SUCCESS =
  "GET_IDENTITY_BY_SESSION_SUCCESS";
export const SAVE_ATTENDANCE = "SAVE_ATTENDANCE";
export const SAVE_ATTENDANCE_SUCCESS = "SAVE_ATTENDANCE_SUCCESS";
export const SEND_COLLOBRATORIDENTITY = "SEND_COLLOBRATORIDENTITY";
export const SEND_COLLOBRATORIDENTITY_SUCCESS =
  "SEND_COLLOBRATORIDENTITY_SUCCESS";
export const REMOVE_IDENTITY = "REMOVE_IDENTITY";
export const UNCHECK_COLLOBRATORIDENTITY = "UNCHECK_COLLOBRATORIDENTITY";

export const TOGGLE_SENTMAIL_MODAL = "TOGGLE_SENTMAIL_MODAL";
export const GET_PLAN_DATA = "GET_PLAN_DATA";
export const GET_PLAN_DATA_SUCCESS = "GET_PLAN_DATA_SUCCESS";
export const CREATE_COURSE = "CREATE_COURSE";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const DELETE_COURSE = "DELETE_COURSE";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const RESPONSESTATUS = "RESPONSESTATUS";
export const RESPONSEMESSAGE = "RESPONSEMESSAGE";
export const GET_MASTER_DATA = "GET_MASTER_DATA";
export const GET_MASTER_DATA_SUCCESS = "GET_MASTER_DATA_SUCCESS";

//Get Role Permission Data
export const GET_ROLE = "GET_ROLE";
export const GET_ROLE_SUCCESS_DATA = "GET_ROLE_SUCCESS_DATA";
export const SAVE_ROLE_DATA = "SAVE_ROLE_DATA";
export const DELETE_ROLE_DATA = "DELETE_ROLE_DATA";
export const GET_PERMISSION = "GET_PERMISSION";
export const GET_PERMISSION_SUCCESS_DATA = "GET_PERMISSION_SUCCESS_DATA";
export const SAVE_PERMISSION_DATA = "SAVE_PERMISSION_DATA";
export const SAVE_PERMISSION_SUCCESS_DATA = "SAVE_PERMISSION_SUCCESS_DATA";

//Sigin With DNI, forgot & change password
export const SIGNIN_USER_DNI = "SIGNIN_USER_DNI";
export const SIGNIN_USER_DNI_SUCCESS = "SIGNIN_USER_DNI_SUCCESS";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const USER_ROLE_PERMISSION = "USER_ROLE_PERMISSION";

//Global
export const SHOW_SUCCESS_MESSAGE = "SHOW_SUCCESS_MESSAGE";
export const SHOW_MESSAGE11 = "SHOW_MESSAGE11";

//Gia configuration
export const GIA_DATA_PENDING = "GIA_DATA_PENDING";
export const GIA_DATA_SUCCESS = "GIA_DATA_SUCCESS";
export const GIA_DATA_FAILURE = "GIA_DATA_FAILURE";
export const GET_GIA_DATA_PENDING = "GET_GIA_DATA_PENDING";
export const GET_GIA_DATA_SUCCESS = "GET_GIA_DATA_SUCCESS";
export const GET_GIA_DATA_FAILURE = "GET_GIA_DATA_FAILURE";

// get synchronize data

export const GET_SYNCHRONIZE_PENDING = "GET_SYNCHRONIZE_PENDING";
export const GET_SYNCHRONIZE_SUCCESS = "GET_SYNCHRONIZE_SUCCESS";
export const GET_SYNCHRONIZE_FAILURE = "GET_SYNCHRONIZE_FAILURE";

//get general settings data

export const GET_GENERAL_SETTINGS_PENDING = "GET_GENERAL_SETTINGS_PENDING";
export const GET_GENERAL_SETTINGS_SUCCESS = "GET_GENERAL_SETTINGS_SUCCESS";
export const GET_GENERAL_SETTINGS_FAILURE = "GET_GENERAL_SETTINGS_FAILURE";
export const GET_DEVICE_NAME_PENDING = "GET_DEVICE_NAME_PENDING";
export const GET_DEVICE_NAME_SUCCESS = "GET_DEVICE_NAME_SUCCESS";
export const GET_DEVICE_NAME_FAILURE = "GET_DEVICE_NAME_FAILURE";
export const ADD_GENERAL_SETTINGS_PENDING = "ADD_GENERAL_SETTINGS_PENDING";
export const ADD_GENERAL_SETTINGS_SUCCESS = "ADD_GENERAL_SETTINGS_SUCCESS";
export const ADD_GENERAL_SETTINGS_FAILURE = "ADD_GENERAL_SETTINGS_FAILURE";

//get select procedure list

export const SELECT_PROCEDURE_PENDING = "SELECT_PROCEDURE_PENDING";
export const SELECT_PROCEDURE_SUCCESS = "SELECT_PROCEDURE_SUCCESS";
export const SELECT_PROCEDURE_FAILURE = "SELECT_PROCEDURE_FAILURE";
export const GET_PROCEDURE_CONFIG_PENDING = "GET_PROCEDURE_CONFIG_PENDING";
export const GET_PROCEDURE_CONFIG_SUCCESS = "GET_PROCEDURE_CONFIG_SUCCESS";
export const GET_PROCEDURE_CONFIG_FAILURE = "GET_PROCEDURE_CONFIG_FAILURE";
export const GET_PROCEDURE_BY_ID_PENDING = "GET_PROCEDURE_BY_ID_PENDING";
export const GET_PROCEDURE_BY_ID_SUCCESS = "GET_PROCEDURE_BY_ID_SUCCESS";
export const GET_PROCEDURE_BY_ID_FAILURE = "GET_PROCEDURE_BY_ID_FAILURE";
export const ADD_PROCEDURE_CONFIG_PENDING = "ADD_PROCEDURE_CONFIG_PENDING";
export const ADD_PROCEDURE_CONFIG_SUCCESS = "ADD_PROCEDURE_CONFIG_SUCCESS";
export const ADD_PROCEDURE_CONFIG_FAILURE = "ADD_PROCEDURE_CONFIG_FAILURE";
export const UPDATE_PROCEDURE_PENDING = "UPDATE_PROCEDURE_PENDING";
export const UPDATE_PROCEDURE_SUCCESS = "UPDATE_PROCEDURE_SUCCESS";
export const UPDATE_PROCEDURE_FAILURE = "UPDATE_PROCEDURE_FAILURE";
export const DELETE_PROCEDURE_PENDING = "DELETE_PROCEDURE_PENDING";
export const DELETE_PROCEDURE_SUCCESS = "DELETE_PROCEDURE_SUCCESS";
export const DELETE_PROCEDURE_FAILURE = "DELETE_PROCEDURE_FAILURE";

export const CLEAR_DATA = "CLEAR_DATA";

export const VIEW_PROCEDURE_DETAIL_PENDING = "VIEW_PROCEDURE_DETAIL_PENDING";
export const VIEW_PROCEDURE_DETAIL_SUCCESS = "VIEW_PROCEDURE_DETAIL_SUCCESS";
export const VIEW_PROCEDURE_DETAIL_FAILURE = "VIEW_PROCEDURE_DETAIL_FAILURE";

export const RESUBMIT_TO_GIA_PENDING = "RESUBMIT_TO_GIA_PENDING";
export const RESUBMIT_TO_GIA_SUCCESS = "RESUBMIT_TO_GIA_SUCCESS";
export const RESUBMIT_TO_GIA_FAILURE = "RESUBMIT_TO_GIA_FAILURE";

//get log management data

export const GET_LOG_MANAGEMENT_DATA_PENDING =
  "GET_LOG_MANAGEMENT_DATA_PENDING";
export const GET_LOG_MANAGEMENT_DATA_SUCCESS =
  "GET_LOG_MANAGEMENT_DATA_SUCCESS";
export const GET_LOG_MANAGEMENT_DATA_FAILURE =
  "GET_LOG_MANAGEMENT_DATA_FAILURE";

//get record count

export const GET_COUNTER_PENDING = "GET_COUNTER_PENDING";
export const GET_COUNTER_SUCCESS = "GET_COUNTER_SUCCESS";
export const GET_COUNTER_FAILURE = "GET_COUNTER_FAILURE";

//get relunch data

export const RELAUNCH_DATA_PENDING = "RELAUNCH_DATA_PENDING";
export const RELAUNCH_DATA_SUCCESS = "RELAUNCH_DATA_SUCCESS";
export const RELAUNCH_DATA_FAILURE = "RELAUNCH_DATA_FAILURE";

//get procedure detail export file

export const GET_EXPORT_PENDING = "GET_EXPORT_PENDING";
export const GET_EXPORT_SUCCESS = "GET_EXPORT_SUCCESS";
export const GET_EXPORT_FAILURE = "GET_EXPORT_FAILURE";
